export const TEMPLATES = [
  {
    id: "t1",
    case: "1",
    name: "Email to Recruiter",
    sub: "Job exists, not applied",
    type: "Email",
    subject: "Data Engineer Role at [Company] — Manikanth Nampally",
    body: "Hi [Recruiter Name],\n\nI came across the Data Engineer opening at [Company] and I’m excited about the opportunity. I have 2+ years building large-scale pipelines with Python, PySpark, Databricks, Airflow, Kafka, and AWS.\n\nI’m submitting my application and would love to connect.\n\nBest,\nManikanth Nampally",
  },
  {
    id: "t2",
    case: "1",
    name: "Email to Hiring Manager",
    sub: "Job exists, not applied",
    type: "Email",
    subject: "Data Engineer Opening at [Company] — Manikanth Nampally",
    body: "Hi [Hiring Manager Name],\n\nI’m reaching out regarding the Data Engineer role on your team. My background in data lakehouse and streaming systems aligns well with this role.\n\nI’m applying today and would value a brief conversation.\n\nBest,\nManikanth Nampally",
  },
  {
    id: "t3",
    case: "1",
    name: "LinkedIn 300 chars to Recruiter",
    sub: "Job exists, not applied",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name], I saw the Data Engineer role at [Company] and I’m very interested. I have 2+ years building large-scale pipelines with PySpark, Databricks, and AWS. I’m applying today and would love to connect.",
  },
  {
    id: "t4",
    case: "1",
    name: "LinkedIn Full to Recruiter",
    sub: "Job exists, not applied",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name],\n\nI came across the Data Engineer opening at [Company] and I’m excited to apply. I bring 2+ years of experience building 35+ TB/day pipelines with PySpark, Databricks, Airflow, Kafka, and AWS.\n\nWould love to connect and learn about next steps.\n\nManikanth",
  },
  {
    id: "t5",
    case: "1",
    name: "LinkedIn 300 chars to Hiring Manager",
    sub: "Job exists, not applied",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name], I noticed the Data Engineer opening on your team at [Company]. My experience with PySpark, Databricks, Kafka, and AWS at scale maps closely to this role. I’m applying today and would appreciate connecting.",
  },
  {
    id: "t6",
    case: "1",
    name: "LinkedIn Full to Hiring Manager",
    sub: "Job exists, not applied",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name],\n\nI’m interested in the Data Engineer role on your team at [Company]. I have hands-on experience with large-scale ETL/ELT and streaming systems using PySpark, Databricks, Airflow, Kafka, and AWS.\n\nI’m applying and would value a quick conversation.\n\nManikanth",
  },
  {
    id: "t7",
    case: "1",
    name: "LinkedIn to Employee Referral",
    sub: "Job exists, not applied",
    type: "LinkedIn",
    subject: "",
    body: "Hey [Name], I found a Data Engineer opening at [Company] that matches my background well. Would you be open to sharing a referral link or referring me? I’d really appreciate your support.",
  },
  {
    id: "t8",
    case: "1",
    name: "WhatsApp to Employee Referral",
    sub: "Job exists, not applied",
    type: "WhatsApp",
    subject: "",
    body: "Hey [Name]! Hope you’re well. I found a Data Engineer opening at [Company]. Could you please share the referral link or refer me? It would really help. Thanks a lot!",
  },
  {
    id: "t9",
    case: "2",
    name: "Email Follow Up to Recruiter",
    sub: "Job exists, already applied",
    type: "Email",
    subject: "Following Up — Data Engineer Application",
    body: "Hi [Recruiter Name],\n\nI wanted to follow up on my Data Engineer application submitted on [date]. I remain excited and would appreciate any update on next steps.\n\nBest,\nManikanth Nampally",
  },
  {
    id: "t10",
    case: "3",
    name: "Cold Email to Recruiter",
    sub: "No opening, cold outreach",
    type: "Email",
    subject: "Connecting — Data Engineer — Manikanth Nampally",
    body: "Hi [Recruiter Name],\n\nI’ve been following [Company] and am impressed by your data platform work. I’d love to be considered for future Data Engineer opportunities and stay connected.\n\nBest,\nManikanth Nampally",
  },
  {
    id: "t11",
    case: "3",
    name: "Cold LinkedIn to Recruiter",
    sub: "No opening, cold outreach",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name], I’ve been following [Company]’s data engineering work and would love to connect. I’m a Data Engineer with experience in PySpark, Databricks, Kafka, and AWS, and would appreciate being considered for future roles.",
  },
  {
    id: "t12",
    case: "4",
    name: "LinkedIn Follow Up No Response",
    sub: "No response follow up",
    type: "LinkedIn",
    subject: "",
    body: "Hi [Name], following up on my previous note regarding Data Engineer opportunities at [Company]. I remain very interested and would appreciate connecting when convenient.",
  },
  {
    id: "t13",
    case: "4",
    name: "Email Follow Up No Response",
    sub: "No response follow up",
    type: "Email",
    subject: "Following Up — Data Engineer",
    body: "Hi [Name],\n\nI’m following up on my earlier message regarding Data Engineer opportunities at [Company]. I remain very interested and would appreciate a quick update when possible.\n\nBest,\nManikanth Nampally",
  },
];
